import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/custom/Header";
import { Montserrat } from "next/font/google";
import { Flex } from "@/components/ui/flex";
import MobileNav from "@/components/custom/MobileNav";

const font = Montserrat({ subsets: ["latin"], weight: ["400"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${font.className} tracking-wide antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableColorScheme
          themes={["dark", "light"]}
        >
          <Header />
          <MobileNav />
          <Flex className="justify-between items-center md:max-w-[80%] mx-auto">
            {children}
          </Flex>
          
        </ThemeProvider>
      </body>
    </html>
  );
}